---

# Currently this role writes out two different configuration
# formats. The old-style Banjax configuration is libconfig based
# and terrible. The new-style YAML configurations are the current
# standard and are in use by Banjax as of August 2015.

- name: Old-style banjax configuration file
  template: src=banjax.conf.j2 dest={{ats_output}}/banjax.conf

- name: Create banjax.d dir
  file: dest={{ats_output}}/banjax.d state=directory

- name: Banjax configuration for {{item.key}}
  template: src=banjax.d.j2 dest={{ats_output}}/banjax.d/{{item.key}}.conf
  when: remap[item.key]["banjax_path"]
  with_dict: remap

- name: Banjax master configuration file
  template: src=banjax.conf.new.j2 dest={{ats_output}}/banjax.conf.new

# Useful for detecting breakage when using old-style banjax
- script: scripts/libconfig_check.py {{ats_output}}/banjax.conf


